coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
    patch:
      default:
        target: 75%
        threshold: 1%

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no

ignore:
  - "src/**/__tests__/**"
  - "src/**/*.test.ts"
  - "src/test.ts"
  - "src/test-enhanced.ts"
  - "dist/**"
  - "coverage/**"
  - "examples/**"
  - "*.md"
