  add-egypt-support[m
  add-tanzania-support[m
  feature/add-ghana[m
  feature/add-ivory-coast[m
* [32mfeature/add-new-countries-drc-uganda-algeria[m
  feature/add-nigeria[m
  feature/add-senegal[m
  feature/improve-user-interface[m
  improve-coverage[m
  main[m
  test-africa-expansion-complete[m
  [31mremotes/origin/add-egypt-support[m
  [31mremotes/origin/feature/add-ghana[m
  [31mremotes/origin/feature/add-ivory-coast[m
  [31mremotes/origin/feature/add-nigeria[m
  [31mremotes/origin/feature/add-senegal[m
  [31mremotes/origin/feature/improve-user-interface[m
  [31mremotes/origin/improve-coverage[m
  [31mremotes/origin/main[m
